#!/usr/bin/env lua

function isEmpty(var)
  return var == nil or var == ''
end

function isNumber(var)
  return type( var ) == "number"
end

function isString(var)
  return type( var ) == "string"
end

function isBoolean(var)
  return type( var ) == "boolean"
end

function isTable(var)
  return type( var ) == "table"
end
